import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import c from "clsx";
import FeatherIcon from 'feather-icons-react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Financial Broker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={c(styles.main)}
      >
        <main
        className={c(styles.main, "bg-backgr3 bg-no-repeat bg-cover bg-center")}
       >
        <div className="responsive">
          <div className="container">
             <div className="mt-3">
                <span className="text-[50px] leading-[44px] font-bold bg-gradient-to-r text-transparent bg-clip-text from-[#8D42E7] via-[#E7429B] to-[#E7A542]">
                Digital era Web3
                </span>
                <div className="grid grid-cols-10 gap-3">
                    <div className="col-span-6">
                      <div className="mt-5">
                        <div className="ml-[30px]">
                          <p className="font-bold text-[25px] text-neutral-50">
                          Web3 is having a profound impact on the media, finance-economics and 
                          education sectors, opening up new opportunities and changing the way 
                          we approach and interact. These potentials have not yet been fully 
                          exploited and there are many aspects left to explore and develop in 
                          the future.
                          </p>
                          <p className="mt-2 font-bold text-[25px] text-neutral-50">
                          The FIE token was created to leverage the potential of Web3 in the 
                          media, finance-economics and education sectors by providing a 
                          decentralized, fair and transparent ecosystem. The FIE token 
                          allows users to access services easily and securely, while creating 
                          access opportunities for those with limited access to products and services.
                          </p>
                          <p className="font-bold text-[25px] text-neutral-50 mt-5">
                          Discover now 
                          </p>
                        </div>
                      </div>
                    </div>
                </div>
          </div>
          </div>
        </div>
      </main>
      </main>
    </>
  )
}
